### ISSUE TITLE
example script

### ISSUE THREAD

**Issue by pi0projects** [project-kaat/gpsdRelay#5]
could you please provide a sample script on how to obtain the gpsd data.

**Comment by project-kaat** [comment]
> could you please provide a sample script on how to obtain the gpsd data.

by obtaining data you mean receiving it on the client side?

**Comment by project-kaat** [comment]
well, anyways. To use this app as a tcp gpsd source you can just launch gpsd on your receiver device like so:
`gpsd tcp://<phone_ip_here>:<phone_port_here>`
Closing the issue
