### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by i8degrees** [project-kaat/gpsdRelay#6]
Hi,

I recently migrated from using the Android app **GPSd Forwarder** to your app, principally because of the simple fact that your app has kept up with the incremental API updates to Android, making it much less of a headache to recompile if I ever deem it necessary.

Why would I ever want to do such? The one feature missing from both apps is an auto-run at startup that also starts the server connection to `gpsd`. I use a spare Android phone as a GPS source for time sync across my LAN as it is critical for many of my internal services to have a stable time source for TFA logins -- my clients and server must be within thirty seconds of each other, else authentication fails.

With the `gpsd` relay, I can easily support HA by simply running this app on more than one phone. Even when all else fails, I can still maintain time sync by running a client here on my personal phone.

Would you be interested in adding an auto -run feature to this app? If not, I have planned on doing it myself once time allows -- unfortunately, I am looking at a severe backlog and cannot say when I can get to it. So, here is to hoping that you are interested enough in supporting the feature yourself.

In any case, thank you for this app. It is on my short list of what I consider mission-critical applications inside of my LAN! :-)

**Comment by i8degrees** [comment]
# summary

For the sake of trying to maintain some sense of organization with this feature request, I am attaching the initial R&D work I have done before making this feature request. Perhaps it will help whomever ultimately decides to implement this feature, be it you or myself.

## methods tried using third-party auto-start

1. `Tasker` profile
  * This method works fine once you follow the pre-requisite steps for granting Tasker the right permissions; this is a 100% GUI solution and is probably preferred by the vast majority. I can confirm that a simple Tasker profile does, in fact, launch the application reliably at the time of startup.

2. Using `Termux-Boot` plugin with Termux to auto-start upon boot via shell script
  * I prefer this method as I am already more comfortable with writing shell scripts. It is a simple one-line script containing something like `pm start io.github.project_kaat.gpsdrelay`.

3. Third-party apps, such as one that is mentioned by a [AirDroid support page](https://www.airdroid.com/app-management/android-auto-launch-app/#) called [AutoStart App Manager](https://play.google.com/store/apps/details?id=com.sugarapps.autostartmanager). I strongly suggest not installing this app, as it serves advertisements after every other click, but if anybody is aware of another auto-start application launcher that is OSS or at least not filled with advertisements, it could be added here, I guess. I am not aware of any, nor have I made any particular attempt.

### issues with third-party auto-start 

If this was the end of the story, I would not have opened this issue; there is still one more step here and this involves executing the functionality of the **Start Server** button. 

I have experimented with using the `input` shell utility to automate the one simple click that we must do, but it is not this simple, for we must assume that the application is started, but still in the background, and thus we must bring it to the foreground somehow and then quickly perform the virtual click before anything else interrupts the process. I have yet to find a solution for performing this reliably, as the OS is still quite busy loading everything else up! I can conceptualize how to do this last action by utilizing a blocking thread, but I dislike this option for what should be obvious to you and everybody else in the software development world.

Perhaps it would be enough for one of us to expose an API consisting of one function that can execute the **Start Server** button action? I have yet to explore the existing codebase sufficiently in order to answer this myself. 

I **just** remembered that you can view and execute existing Application intents from within a third-party app, of which I will have to spend a few minutes hunting down the right version of at a later point. Perhaps you already have registered the necessary intent to execute this button without any further work?

## TODO

### SYSTEM_ALERT_WINDOW permission

Ugh, now I do not recall why I wanted to try this, but... I have yet to try enabling [SYSTEM_ALERT_WINDOW][1] for `gpsdrelay`. 

[1]: https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW>

```shell
adb shell pm grant \
io.github.project_kaat.gpsdrelay.android.permission.SYSTEM_ALERT_WINDOW
```

## reference documents

1. <https://developer.android.com/topic/libraries/app-startup>
1. <https://www.digi.com/resources/documentation/digidocs/embedded/android/pie/cc8x/android_t_autostart-apps#>

**Comment by project-kaat** [comment]
Hey...

First of all - sorry for an entire month of silence. It's obvious that I currently have no interest in this github account and any of its projects.

That said, I have no problem implementing this feature by exposing the **START SERVER** action (and the **STOP SERVER** action while I'm at it) through a simple broadcast receiver, which can be triggered with the standard `am` utility. 

I'd prefer to implement it as a checkbox in the preferences but the app itself lacks the logic. It was not written with automation in mind.

So whether this request is still relevant or not, I'll try to get that done (hopefully in under a week).

**Comment by project-kaat** [comment]
Implemented in https://github.com/project-kaat/gpsdRelay/commit/b1bcc747922b5ad52822013ea0e43055c14d7d71.

**Comment by i8degrees** [comment]
Omg, it was like Christmas day all over again when I finally remembered to check back here to see if there were any updates. 

Thank you @project-kaat. I figured that it was a 50/50 shot at receiving a response here. I knew that if nothing else, it would serve as a reminder to myself to maybe some day get around to looking into this again.  

I am afraid that I have been busy with other things in my life and whereas I would love nothing more than to spend my life here, I must continue pushing onwards elsewhere before I can get my life settled. Better late than never, though, right? :-D

> I'd prefer to implement it as a checkbox in the preferences but the app itself lacks the logic. It was not written with automation in mind.

> So whether this request is still relevant or not, I'll try to get that done (hopefully in under a week).

The request is still relevant to me and shall be very useful to me once I find another opportunity to revisit my use case for this. Unfortunately, the only working phone at the time for this project is no longer feasible, **but** just as soon as I am able to sit down and solder a few wires together, I have another phone to employ with this project in mind.

In the mean time, I have already downloaded the latest release and will be testing it out here on my primary driver here soon after posting this comment. I am quite excited to see if it works and will report back the results here.

Thank you once again!

Happy New Year -- Cheers,
Jeff

**Comment by i8degrees** [comment]
# Preliminary test results

## Service autostart

**STUB**: Figured I would post the results here. I promise it won't be months this time around before I reply back here! :-)

## Network timeout

I wanted to say that I appreciate that you implemented stopping the service in case the network times out. I have discovered during my attempts with using a mobile phone as a GPS source that the WiFi chipsets in older phones, especially, tend to be, well, buggy and unreliable. After some amount of time (often measurable in days), the WiFi network will die and never come back until either you reboot the device or sometimes if you are lucky, you can just toggle it back on and off.

In any case, stopping the service when there is no network should conserve a significant amount of battery, so thank you for thinking ahead on that.

**Comment by i8degrees** [comment]
So, I tried this on two Android mobiles -- Google Pixel 4XL (Android 13) and Stratus C5 (cheap, chinese phone) with Android 11. Both phones are rooted.

After installing the app and setting it up with all my settings... I checked the autostart feature and away I went -- with a swift reboot and logging back in... I was not surprised that it did not start up on its own with my Pixel, after reading the note you wrote in the app warning about Android 12 and above...

So, I tried sending a broadcast via `adb shell` like so (while also keeping `gpsdRelay` in the foreground):

```shell
adb shell am broadcast -a io.github.project_kaat.action.STOP_SERVICE
Broadcasting: Intent { act=io.github.project_kaat.action.STOP_SERVICE flg=0x400000 }
Broadcast completed: result=0
```

1. I expected to see the service stop after sending the first command.

```shell
adb shell am broadcast -a io.github.project_kaat.action.START_SERVICE
Broadcasting: Intent { act=io.github.project_kaat.action.START_SERVICE flg=0x400000 }
Broadcast completed: result=0
```

1. I expected to see the service start after sending this command.

Now, on my other phone, the Stratus C5, I repeat the above and a not so swift reboot of the phone...

I never saw `gpsdRelay` start back up on its own. :-( I was unable to (yet) test the command set that I did with the Pixel phone. I assume that I am doing something wrong! :-) I will try again tomorrow when I am better rested. If you have any comments, I would do my best to respond.

**Comment by project-kaat** [comment]
First of all, yeah I'll admit the app straight up sucks from the user experience standpoint.

For this reason, I have been working on version 2.0, rewritten entirely in Compose and targetting Android 15.
The goal was to finish it before the holiday season but it's just too much work. It is, however, almost ready and will be out _soon_.

Now, to address your troubles.
Basically, Android 12+ makes it **quite** a pain to start a location service in the background.
That, combined with the fact that I do not have any physical Android 12+ devices for testing make the implementation a bit iffy.

**However:**
 1. In the process of working on the 2.0, I realized how the old version does not ask for background location permissions at all. This needs to be resolved by manually going into Settings, tapping on the Location permission in the app's permission list and choosing "Allow all the time" (along with precise/coarse location permission). It was not explained anywhere and is entirely my fault.
 2. When using broadcasts, you need to specify the receiver in the command. Otherwise the broadcast simply won't reach the endpoint. I will have to do a writeup on how to do this later and put a link to it in a little "Help" submenu in the 2.0.
 
 I do not have much time right now to test properly but I just **created an emulator** of a Pixel 4XL running Android 13 and **installed the current version of the app (1.3)**, went into the app's settings tab and **checked the autostart checkbox**, went into the Android Settings and **manually granted the background location and precise location permissions**.
These actions resulted in a successfull automatic start upon a reboot and I was able to receive data in gpsd on my machine.

I hope this will clear some things up. If not - I promise the 2.0 will provide a more polished experience :)

**Comment by project-kaat** [comment]
> I promise the 2.0 will provide a more polished experience :)

At least until Android 16 comes out with some more artificial restrictions that is :P
