### ISSUE TITLE
time is not given as UTC but in local time

### ISSUE THREAD

**Issue by HoWilgh** [project-kaat/gpsdRelay#8]
The time sent is not the time in utc, while it lists it as utc.
The sent time is in 'local' time-zone set on the android device.

When red on a ubuntu-linux device using cgps, one gets something like 
`'time': datetime.datetime(2024, 11, 22, 17, 51, 26, tzinfo=datetime.timezone.utc),`
 which was the local time shown on the device and should be 
`'time': datetime.datetime(2024, 11, 22, 16, 51, 26, tzinfo=datetime.timezone.utc),`
for local time set to 'UTC+1'. 

Maybe compare with https://github.com/tiagoshibata/Android-GPSd-Forwarder

**Comment by project-kaat** [comment]
oops...
Thanks for reporting

**Comment by project-kaat** [comment]
fixed in 933444e1923232e66c0cbc838d7a0ee424b2c85d
